apiVersion: v2
description: FFC demo service event stream consumer
name: ffc-demo-collector
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^1.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
